### ISSUE TITLE
Help adding Biomes as Rivers

### ISSUE THREAD

**Issue by vivagabe** [zehmaria/createpickywheels#2]
Im really enjoying this mod but im at a loss as to how to add more biomes as "rivers". Regions Unexplored has a few other river biomes (cold river, muddy river, etc..) and i would like for them to work with the wheels; can you offer any advice?

**Comment by zehmaria** [comment]
This has been fixed for 1.20.1, and it is up on curseforge. The other versions will come in a bit.
